.\" Manpage for ProCalc.
.\" Contact anton2920@gmail.com for comments or help.
.TH man 1 "23 Mar 2019" "1.0" "ProCalc man page"
.SH NAME
ProCalc
.SH SYNOPSIS
ProCalc
.SH DESCRIPTION
ProCalc is a free powerful multifunctional calculator.
.SH OPTIONS
ProCalc does not take any arguments.
.SH BUGS
No known bugs.
.SH AUTHOR
Tushino Software LLC (anton2920@gmail.com)
