.\" Manpage for ProCalc.
.\" Contact anton2920@gmail.com for comments or help.
.TH man 1 "06 Apr 2019" "1.0" "ProTest man page"
.SH NAME
ProCalc
.SH SYNOPSIS
ProCalc
.SH DESCRIPTION
ProTest is a free powerful program for educational tests.
.SH OPTIONS
ProTest does not take any arguments.
.SH BUGS
No known bugs.
.SH AUTHOR
Tushino Software LLC (anton2920@gmail.com)
